apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: simple-go-todo

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: todo-api
        resources:
          requests:
            cpu: "500m" # I need access to 1/2 core on the node.
          limits:
            cpu: "500m" # Execute instructions 50ms/100ms on my 1 core.s