apiVersion: v1
kind: Namespace
metadata:
  name: todo-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo-service

  spec:
    selector:
      matchLabels:
        app: todo
    
    template:
      metadata:
        labels:
          app: todo
      spec:
        terminationGracePeriodSeconds: 60
        containers:
        - name: todo-api
          image: service-image

          ports: 
          - name: todo-api
          containerPort: 8000

          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: todo-service

spec:
  selector:
    app: todo