apiVersion: v1
kind: Namespace
metadata:
  name: simple-go-todo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: simple-go-todo

spec:
  selector:
    matchLabels:
      app: todo

  template:
    metadata:
      labels:
        app: todo

    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: todo-api
        image: service-image
        env:
        - name: DB_HOST
          value: localhost
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: changeme
        - name: DB_NAME
          value: todo
        - name: DB_PORT
          value: "5432"
        
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: simple-go-todo

spec:
  selector:
    app: todo